### ISSUE TITLE
compiling error :)

### ISSUE THREAD

**Issue by xpression13377** [clauadv/hunt_internal#1]
Error (active)	E0135	class "std::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "contains"	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	29	
Error (active)	E0135	class "std::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "contains"	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	43	
Error (active)	E0135	class "std::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "contains"	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	57	
Error (active)	E0135	class "std::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "contains"	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	72	
Error (active)	E0135	class "std::basic_string<char, std::char_traits<char>, std::allocator<char>>" has no member "contains"	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	86	
Error	C2039	'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	29	
Error	C2039	'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	43	
Error	C2039	'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	57	
Error	C2039	'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	72	
Error	C2039	'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	hunt_internal	C:\Users\Desktop\hunt_internal-main\hunt_internal\cry_engine\cry_entity_system\entity.cpp	86	
![error](https://user-images.githubusercontent.com/109007011/178127637-346a2f67-e67e-46e0-b7f9-39bde35f12e9.png)
basically this 10x

**Comment by clauadv** [comment]
u need v143 toolset and latest cpp version in project settings

**Comment by xpression13377** [comment]
thanks :)

**Comment by clauadv** [comment]
no problem
